version: '3.8'

services:
  # ------------------------------------
  # BASES DE DATOS
  # ------------------------------------
  postgres-mantenimiento:
    image: postgres:15-alpine
    container_name: db_mantenimiento
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mantenimiento_db
    ports:
      - "5432:5432"
    restart: always

  db-proveedor:
    image: postgres:15-alpine
    container_name: db_proveedor
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: proveedor_db
    ports:
      - "5433:5432"
    restart: always

  db-registro:
    image: postgres:15-alpine
    container_name: db_registro
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: registro_db
    ports:
      - "5434:5432"
    restart: always

  db-auth:
    image: postgres:15-alpine
    container_name: db_auth
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5435:5432"
    restart: always

  db-contabilidad:
    image: postgres:15-alpine
    container_name: db_contabilidad
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: contabilidad_db
    ports:
      - "5436:5432"
    restart: always

  # ------------------------------------
  # MICROSERVICIOS (SPRING BOOT)
  # ------------------------------------
  app-mantenimiento:
    build: ./mantenimiento
    container_name: ms_mantenimiento
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-mantenimiento:5432/mantenimiento_db
      - PROVEEDOR_URL=http://app-proveedor:8081/api/proveedores
    depends_on:
      - postgres-mantenimiento

  app-proveedor:
    build: ./proveedor
    container_name: ms_proveedor
    networks:
      - app-network
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-proveedor:5432/proveedor_db
      - SERVER_PORT=8081
    depends_on:
      - db-proveedor

  app-registro:
    build: ./registro
    container_name: ms_registro
    networks:
      - app-network
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-registro:5432/registro_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8082
    depends_on:
      - db-registro
  
  app-contabilidad:
    build: ./contabilidad
    container_name: ms_contabilidad
    networks:
      - app-network
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-contabilidad:5432/contabilidad_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8083
    depends_on:
      - db-contabilidad
  
  app-frontend:
    build: ./Frontend
    container_name: ui_frontend
    networks:
      - app-network
    ports:
      - "3000:80"
    depends_on:
      - app-bff

  app-bff:
    build: ./backend-for-front
    container_name: ms_bff
    networks:
      - app-network
    ports:
      - "9000:9000"
    environment:
      #nombres de los servicios definidos arriba
      - URL_MANTENIMIENTO=http://app-mantenimiento:8080
      - URL_PROVEEDOR=http://app-proveedor:8081
      - URL_REGISTRO=http://app-registro:8082
      - URL_AUTH=http://app-auth:8085
    depends_on:
      - app-mantenimiento
      - app-proveedor
      - app-registro

  app-auth:
    build: ./auth
    container_name: ms_auth
    networks:
      - app-network
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-auth:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8085
    depends_on:
      - db-auth

  app-documentos:
    build: ./documentos
    container_name: ms_documentos
    networks:
      - app-network
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - MINIO_URL=http://minio_storage:9000 
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin1234
    depends_on:
      - minio_storage

  # ------------------------------------
  # ALMACENAMIENTO S3 (MINIO)
  # ------------------------------------
  minio_storage:
    image: minio/minio:latest
    container_name: minio_storage
    networks:
      - app-network
    ports:
      - "9005:9000" # API de S3
      - "9001:9001" # Consola Gráfica Web
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # --- RED ---
networks:
  app-network:
    driver: bridge

volumes:
  minio_data: