spring.application.name=auth

server.port=8085

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/condominio_auth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=clave-secreta-muy-larga-para-firmar-tokens-jwt-condominio-2026
jwt.expiration=86400000
