spring.application.name=backend-for-front
server.port=9000

url.mantenimiento=http://ms_mantenimiento:8080
url.proveedor=http://ms_proveedor:8081
url.registro=http://ms_registro:8082

logging.level.org.springframework.web.reactive.function.client.WebClient=DEBUG